sudo: required
language: generic
services:
  -docker

before_install:
  - docker build -t vini02/docker-react -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true vini02/docker-react npm run test -- --coverage
