sudo: required
language: generic

services:
  -docker

before_install:
  - docker build -t vini02/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true vini02/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learn-docker-react"
  env: "Learndockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-656105953289"
  bucket_path: "learn-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
